### ISSUE TITLE
下载按钮无法显示（部分情况）

### ISSUE THREAD

**Issue by needtocalmdown** [qinlili23333/cxstarDownloader#2]
最近上学校的畅想之星，准备用此插件下书。发现那个网站有两种 试读模式 ，其中一种没有批量下载按钮。望修复，感谢

有下载按钮的页面
https://www.cxstar.com/onlinebook?ruid=21de3be30012bcXXXX&pinst=1df18a8a0006830bce&typecode=ebook&pageno=

无下载按钮的页面
https://www.cxstar.com/onlineepub?ruid=28e49be0000ab5XXXX&school=1df18a8a0006830bce&paraix=&typecode=ebook&booktype=pdf

**Comment by qinlili23333** [comment]
epub不支持，以后也不会支持，我已经离开国内校园网了
